"""Residual gate for the production branch's stage-aware CMC lapse.

The returned lapse is checked against the same discrete K RHS used by the
production geometry step across multiple initial states/grid spacings and on
the actual predictor/final slices generated by one controlled production step.
No long trajectory or physical interpretation is asserted here.
"""
import copy

import numpy as np
import pytest

from engine.production_kernel import V55ProductionKernel, adapter


_CMC_TOL = 1.0e-10


def _assert_cmc_solution(grid, geometry, scalars, matter, alpha, kdot_target, label):
    solved_geometry = copy.deepcopy(geometry)
    solved_geometry.alpha = np.array(alpha, copy=True)

    _, vacuum, _ = adapter.vendor_modules()
    l2 = vacuum.primary_l2_rhs(grid, solved_geometry)
    l3 = adapter.primary_l3_with_matter(
        grid,
        solved_geometry,
        scalars,
        matter,
    )
    k_rhs = l2["K"] + l3["K"]

    assert np.all(np.isfinite(alpha)), f"{label}: non-finite lapse"
    assert np.all(np.asarray(alpha) > 0.0), (
        f"{label}: non-positive lapse; min alpha="
        f"{float(np.min(alpha)):.17e}"
    )
    assert np.isclose(alpha[-1], 1.0), (
        f"{label}: outer lapse normalization is not alpha(R)=1"
    )
    residual = float(np.max(np.abs(k_rhs[:-1] - kdot_target)))
    assert residual < _CMC_TOL, (
        f"{label}: production CMC lapse does not satisfy the discrete "
        f"constant-K RHS; max interior residual={residual:.17e}, "
        f"projected target={kdot_target:.17e}"
    )


@pytest.mark.parametrize(
    "resolution,r_max,D_amplitude,include_radiation",
    [
        (32, 16.0, 1.0e-10, True),
        (64, 16.0, 1.0e-4, True),
        (48, 24.0, 0.0, False),
    ],
    ids=[
        "baseline-D-radiation",
        "higher-resolution-strong-D",
        "larger-domain-D0-no-radiation",
    ],
)
def test_production_cmc_lapse_makes_discrete_k_rhs_spatially_constant(
    resolution, r_max, D_amplitude, include_radiation
):
    kernel = V55ProductionKernel()
    state = kernel.initialize(
        resolution=resolution,
        r_max=r_max,
        D_amplitude=D_amplitude,
        include_radiation=include_radiation,
    )

    alpha, kdot_target = kernel._solve_lapse(
        state.grid,
        state.geometry,
        state.scalars,
        state.matter,
    )
    _assert_cmc_solution(
        state.grid, state.geometry, state.scalars, state.matter,
        alpha, kdot_target,
        label=(
            f"initial slice N={resolution}, r_max={r_max}, "
            f"D={D_amplitude}, radiation={include_radiation}"
        ),
    )


def test_production_cmc_residual_holds_on_actual_predictor_and_final_slices(
    monkeypatch,
):
    """Check the lapse returned inside step(), not only a fresh initialization."""
    kernel = V55ProductionKernel()
    state = kernel.initialize(
        resolution=32,
        r_max=16.0,
        D_amplitude=1.0e-10,
        include_radiation=True,
    )

    original_solve = kernel._solve_lapse
    solve_records = []

    def traced_solve(grid, geometry, scalars, matter):
        # Snapshot exactly the pre-solve slice whose projected target is used.
        geometry_in = copy.deepcopy(geometry)
        scalars_in = copy.deepcopy(scalars)
        matter_in = copy.deepcopy(matter)
        alpha, kdot_target = original_solve(
            grid, geometry, scalars, matter
        )
        solve_records.append({
            "geometry": geometry_in,
            "scalars": scalars_in,
            "matter": matter_in,
            "alpha": np.array(alpha, copy=True),
            "kdot_target": float(kdot_target),
        })
        return alpha, kdot_target

    monkeypatch.setattr(kernel, "_solve_lapse", traced_solve)
    final_state = kernel.step(state, 2.0e-3)

    # The step's four solves are: initial stage, pre-primary predictor,
    # primary-updated predictor used for RHS1, and completed accepted slice.
    assert len(solve_records) == 4, (
        f"expected four stage-aware CMC solves, got {len(solve_records)}"
    )

    for index, label in (
        (2, "primary-updated predictor / RHS1"),
        (3, "completed accepted slice"),
    ):
        record = solve_records[index]
        _assert_cmc_solution(
            state.grid,
            record["geometry"],
            record["scalars"],
            record["matter"],
            record["alpha"],
            record["kdot_target"],
            label=label,
        )

    np.testing.assert_array_equal(
        final_state.geometry.alpha,
        solve_records[3]["alpha"],
        err_msg="accepted state does not retain its own final CMC solve output",
    )
