"""Deterministic stage-synchronization checks for the V5.5 production step.

No trajectory is interpreted here. The gate checks that predictor RHS calls
consume synchronized geometry/scalar/matter states and that scalar/matter
correctors use the matching two RHS evaluations.
"""
import numpy as np

from engine.production_kernel import V55ProductionKernel


_GEOMETRY_FIELDS = ("a", "b", "X", "alpha", "beta", "Aa", "K", "Lambda", "B")
_SCALAR_FIELDS = ("S", "PS", "D", "PD", "phi", "Pi")
_SPECIES = ("dark_matter", "baryons", "radiation")
_CONSERVED_FIELDS = ("rest", "energy_t", "momentum_r")


def _snapshot(state):
    return {
        "geometry": {
            name: np.array(getattr(state.geometry, name), copy=True)
            for name in _GEOMETRY_FIELDS
        },
        "scalars": {
            name: np.array(getattr(state.scalars, name), copy=True)
            for name in _SCALAR_FIELDS
        },
        "matter": {
            species: {
                name: np.array(
                    getattr(getattr(state.matter, species), name), copy=True
                )
                for name in _CONSERVED_FIELDS
            }
            for species in _SPECIES
        },
    }


def _assert_array_equal(actual, expected, message):
    try:
        np.testing.assert_array_equal(actual, expected)
    except AssertionError as exc:
        raise AssertionError(message) from exc


def test_step_uses_synchronized_predictor_and_matching_heun_rhs(monkeypatch):
    kernel = V55ProductionKernel()
    state = kernel.initialize(
        resolution=32, r_max=16.0, D_amplitude=1.0e-10,
        include_radiation=True,
    )
    dt = 2.0e-3
    initial_scalars = {
        name: np.array(getattr(state.scalars, name), copy=True)
        for name in _SCALAR_FIELDS
    }
    initial_matter = {
        species: {
            name: np.array(getattr(getattr(state.matter, species), name), copy=True)
            for name in _CONSERVED_FIELDS
        }
        for species in _SPECIES
    }

    original_rhs = kernel._rhs
    calls = []

    def traced_rhs(stage_state):
        stage_snapshot = _snapshot(stage_state)
        rhs_scalar, rhs_matter, derivatives = original_rhs(stage_state)
        calls.append((stage_snapshot, rhs_scalar, rhs_matter, derivatives))
        return rhs_scalar, rhs_matter, derivatives

    monkeypatch.setattr(kernel, "_rhs", traced_rhs)
    final_state = kernel.step(state, dt)

    assert len(calls) == 2, (
        "one synchronized initial RHS and one synchronized predictor RHS expected"
    )
    stage0, rhs0_scalar, rhs0_matter, _ = calls[0]
    stage1, rhs1_scalar, rhs1_matter, _ = calls[1]

    # The predictor passed to RHS1 must contain the explicit Euler update
    # generated by RHS0 for every scalar and all conservative fluid variables.
    for name in _SCALAR_FIELDS:
        _assert_array_equal(
            stage1["scalars"][name],
            initial_scalars[name] + dt * getattr(rhs0_scalar, name),
            f"predictor scalar {name} is not synchronized to RHS0",
        )
    for species in _SPECIES:
        for name in _CONSERVED_FIELDS:
            _assert_array_equal(
                stage1["matter"][species][name],
                initial_matter[species][name]
                + dt * getattr(rhs0_matter[species], name),
                f"predictor {species}.{name} is not synchronized to RHS0",
            )

    # Each RHS stage must see a lapse solved on that same stage's geometry,
    # scalar fields, and matter state, rather than a stale lapse from another
    # time level. Shift is fixed to zero in this CMC branch.
    for label, snapshot in (("initial", stage0), ("predictor", stage1)):
        geometry = state.geometry.copy()
        for name in _GEOMETRY_FIELDS:
            getattr(geometry, name)[:] = snapshot["geometry"][name]
        from engine.scalar_system import ScalarFields
        from engine.v55_matter import V55MatterState
        from engine.matter_system import ConservedSpecies

        scalars = ScalarFields(**snapshot["scalars"])
        matter = V55MatterState(
            *(
                ConservedSpecies(
                    **snapshot["matter"][species]
                )
                for species in _SPECIES
            )
        )
        expected_alpha, _ = kernel._solve_lapse(
            state.grid, geometry, scalars, matter
        )
        _assert_array_equal(
            snapshot["geometry"]["alpha"], expected_alpha,
            f"{label} RHS used a stale or unsolved CMC lapse",
        )
        _assert_array_equal(
            snapshot["geometry"]["beta"], np.zeros_like(expected_alpha),
            f"{label} RHS stage did not use the zero-shift CMC branch",
        )

    # The accepted matter/scalar state must use the trapezoidal pairing of
    # exactly those two stage RHS evaluations.
    for name in _SCALAR_FIELDS:
        expected = initial_scalars[name] + 0.5 * dt * (
            getattr(rhs0_scalar, name) + getattr(rhs1_scalar, name)
        )
        _assert_array_equal(
            getattr(final_state.scalars, name), expected,
            f"accepted scalar {name} did not use matching RHS0/RHS1",
        )
    for species in _SPECIES:
        for name in _CONSERVED_FIELDS:
            expected = initial_matter[species][name] + 0.5 * dt * (
                getattr(rhs0_matter[species], name)
                + getattr(rhs1_matter[species], name)
            )
            _assert_array_equal(
                getattr(getattr(final_state.matter, species), name), expected,
                f"accepted {species}.{name} did not use matching RHS0/RHS1",
            )

    # The caller's start state is not mutated in place by predictor formation.
    for name in _SCALAR_FIELDS:
        _assert_array_equal(
            getattr(state.scalars, name), initial_scalars[name],
            f"input scalar {name} was mutated during the step",
        )
    for species in _SPECIES:
        for name in _CONSERVED_FIELDS:
            _assert_array_equal(
                getattr(getattr(state.matter, species), name),
                initial_matter[species][name],
                f"input {species}.{name} was mutated during the step",
            )
